services:
  back:
    build: ./back
    networks: [app-net]

  front:
    build: ./front
    ports:
      - "8080:80"        # host:container (só o front é exposto ao usuário)
    depends_on: [back]
    networks: [app-net]

networks:
  app-net:
